name: CI

on:
  push:
  pull_request:
  schedule:
   - cron: '12 8 * * 2'  # 8:12 on Tuesdays

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./manylinux2014_x86_64/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: ghcr.io/libertem/manylinux2014_x86_64:latest

  linux-aarch64:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./manylinux2014_aarch64/Dockerfile
        platforms: linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ghcr.io/libertem/manylinux2014_aarch64:latest
